# Generated by Django 5.0.6 on 2024-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('lunch_basic', models.IntegerField(default=0)),
                ('lunch_premium', models.IntegerField(default=0)),
                ('dinner_basic', models.IntegerField(default=0)),
                ('dinner_premium', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
