# Generated by Django 5.0.6 on 2024-05-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_orderstatistics_delete_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealoff',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.subscriptionplan'),
        ),
    ]
